####################################################################################################
####################################### 网关配置 开始 ##################################
####################################################################################################
server:
  # 配置服务端口号
  port: 7201

spring:
  application:
    # 配置Spring应用名称，也是微服务的名称，SpringCloud中微服务可以有多个实例，实例通过该名称进行分组
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 默认false
          enabled: true
      routes:
        # http://localhost:7201/order-service-route/payment/1 -> http://cloud-consumer-order-openfeign-service/payment/1
        - id: order-service-route
          uri: lb://cloud-consumer-order-openfeign-service
          predicates:
            - Path=/order-service-route/**
          filters:
            - StripPrefix=1
#            - PrefixPath=/order-service-route

eureka:
  client:
    # 配置是否向Eureka服务治理中心进行注册，生产端需要进行注册（不设置默认true）
    register-with-eureka: true
    # 配置是否从服务治理中心拉取服务注册信息，通常只有消费者需要设置为true（不设置默认true）
    fetch-registry: true
    serviceUrl:
      # 这里可以只配部分Eureka治理中心地址，注册信息会互相拉取，这里只配置一个治理中心，在其他治理中心中也能拉取到服务注册信息
      defaultZone: http://node1:7001/eureka,http://node2:7002/eureka
#      defaultZone: http://node2:7002/eureka
  instance:
    prefer-ip-address: true

####################################################################################################
####################################### 网关配置 结束 ##################################
####################################################################################################