server:
  port: 9101

spring:
  application:
    name: cloud-consumer-order-openfeign-service

eureka:
  client:
    # true表示将自己注册进EurekaServer，默认true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合Ribbon使用负载均衡
    fetch-registry: true
    serviceUrl:
      defaultZone: http://node1:7001/eureka,http://node2:7002/eureka


# 超时控制，两种方式都生效，默认1秒，两种都配置的话实测feign配置生效或者优先级高
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000

feign:
  client:
    config:
      default:
        read-timeout: 3000
        connect-timeout: 3000