server:
  port: 9101

spring:
  application:
    name: cloud-consumer-order-openfeign-service

eureka:
  client:
    # true表示将自己注册进EurekaServer，默认true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合Ribbon使用负载均衡
    fetch-registry: true
    serviceUrl:
      defaultZone: http://node1:7001/eureka,http://node2:7002/eureka
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
  MaxAutoRetries: 0
