server:
  port: 8001

spring:
  application:
    name: cloud-provider-payment-service

eureka:
  client:
    # true表示将自己注册进EurekaServer，默认true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合Ribbon使用负载均衡
    # 服务提供方不需要配置为true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://node1:7001/eureka,http://node2:7002/eureka

  # 非必须
  instance:
    instance-id: payment-8001
    prefer-ip-address: true
    # Eureka客户端向服务器发送心跳的时间间隔，单位为秒（默认是30秒）
    lease-renewal-interval-in-seconds: 1
    # Eureka服务端在收到最后一次心跳后等待时间的上限，单位为秒（默认是90秒），超时将剔除服务
    lease-expiration-duration-in-seconds: 2