####################################################################################################
####################################### 服务消费者熔断相关配置 开始 ##################################
####################################################################################################
server:
  # 配置服务端口号
  port: 9201

spring:
  application:
    # 配置Spring应用名称，也是微服务的名称，SpringCloud中微服务可以有多个实例，实例通过该名称进行分组
    name: cloud-consumer-order-ribbon-hystrix-service

eureka:
  client:
    # 配置是否向Eureka服务治理中心进行注册，消费端可以不需要进行注册（不设置默认true）
    register-with-eureka: false
    # 配置是否从服务治理中心拉取服务注册信息，通常只有消费端需要设置为true（不设置默认true）
    # 服务调用方需要设置为true，否则抛出java.lang.IllegalStateException: No instances available for CLOUD-PROVIDER-PAYMENT-SERVICE异常
    fetch-registry: true
    # 检索服务实例清单的时间间隔（单位：秒），默认30秒
    registry-fetch-interval-seconds: 30
    # 当服务获取超时后，最大尝试次数，默认10次
    cache-refresh-executor-exponential-back-off-bound: 10
    # 这里可以只配部分Eureka治理中心地址，注册信息会互相拉取，这里只配置一个治理中心，在其他治理中心中也能拉取到服务注册信息
    serviceUrl:
      defaultZone: http://node1:7001/eureka,http://node2:7002/eureka
#      defaultZone: http://node1:7001/eureka


ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 3000


####################################################################################################
####################################### 服务消费者熔断相关配置 结束 ##################################
####################################################################################################