####################################################################################################
####################################### 单机版服务消费者配置 开始 ##################################
####################################################################################################
server:
  # 配置服务端口号
  port: 9000

spring:
  application:
    # 配置Spring应用名称，也是微服务的名称，SpringCloud中微服务可以有多个实例，实例通过该名称进行分组
    name: cloud-consumer-order-service

eureka:
  client:
    # 配置是否向Eureka服务治理中心进行注册，消费端可以不需要进行注册（不设置默认true）
    register-with-eureka: false
    # 配置是否从服务治理中心拉取服务注册信息，消费端必须设置为true（不设置默认true）
    # 服务调用方需要设置为true，否则抛出java.lang.IllegalStateException: No instances available for CLOUD-PROVIDER-PAYMENT-SERVICE异常
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:7000/eureka
####################################################################################################
####################################### 单机版服务消费者配置 结束 ##################################
####################################################################################################