####################################################################################################
####################################### 集群版服务生产者配置 开始 ##################################
####################################################################################################
server:
  # 配置服务端口号
  port: 8002

spring:
  application:
    # 配置Spring应用名称，也是微服务的名称，SpringCloud中微服务可以有多个实例，实例通过该名称进行分组
    name: cloud-provider-payment-service

eureka:
  client:
    # 配置是否向Eureka服务治理中心进行注册，生产端需要进行注册（不设置默认true）
    register-with-eureka: true
    # 配置是否从服务治理中心拉取服务注册信息，通常只有消费者需要设置为true（不设置默认true）
    fetch-registry: false
    serviceUrl:
      # 这里可以只配部分Eureka治理中心地址，注册信息会互相拉取，这里只配置一个治理中心，在其他治理中心中也能拉取到服务注册信息
      defaultZone: http://node1:7001/eureka,http://node2:7002/eureka
#      defaultZone: http://node2:7002/eureka

  # 非必须
  instance:
    instance-id: payment-8002
    prefer-ip-address: true
    # Eureka客户端向服务器发送心跳的时间间隔，单位为秒（默认是30秒）
    lease-renewal-interval-in-seconds: 10
    # Eureka服务端在收到最后一次心跳后等待时间的上限，单位为秒（默认是90秒），超时将剔除服务
    lease-expiration-duration-in-seconds: 30
####################################################################################################
####################################### 集群版服务生产者配置 开始 ##################################
####################################################################################################