####################################################################################################
####################################### 单机版服务注册中心配置 开始 ##################################
####################################################################################################
server:
  # 配置服务端口号
  port: 7000

spring:
  application:
    # 配置Spring应用名称，也是微服务的名称，SpringCloud中微服务可以有多个实例，实例通过该名称进行分组
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    # 配置是否寻找其他Eureka服务注册中心进行注册，单机版Eureka服务不需要注册，设置为false（不设置默认true）
    register-with-eureka: false
    # 配置是否从服务配置中心拉取服务注册信息，通常只有消费者需要设置为true（不设置默认true）
    fetch-registry: false
#    server-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

####################################################################################################
####################################### 单机版服务注册中心配置 结束 ##################################
####################################################################################################