####################################################################################################
####################################### 单机版服务生产者配置 开始 ##################################
####################################################################################################
server:
  # 配置服务端口号
  port: 8000

spring:
  application:
    # 配置Spring应用名称，也是微服务的名称，SpringCloud中微服务可以有多个实例，实例通过该名称进行分组
    name: cloud-provider-payment-service

eureka:
  client:
    # 配置向Eureka服务治理中心进行注册，生产端需要进行注册（不设置默认true）
    register-with-eureka: true
    # 配置是否从服务治理中心拉取服务注册信息，通常只有消费者需要设置为true（不设置默认true）
    fetch-registry: false
    # 配置Eureka服务治理中心地址
    serviceUrl:
      defaultZone: http://localhost:7000/eureka
####################################################################################################
####################################### 单机版服务生产者配置 结束 ##################################
####################################################################################################