server:
  port: 7001

eureka:
  instance:
    hostname: localhost
  client:
    # false表示不像注册中心注册自己
    register-with-eureka: false
    # false
    fetch-registry: false
    server-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/