
spring:
  application:
    name: eureka-server

server:
  port: 7000


eureka:
  instance:
    hostname: localhost
  client:
    # 服务本身就是注册中心，需要设置为false取消注册（不设置默认true）
    register-with-eureka: false
    # 设置不拉取服务注册信息
    fetch-registry: false
#    server-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/