server:
  port: 7001

eureka:
  instance:
    hostname: node1
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    # false表示不像注册中心注册自己
    register-with-eureka: false
    # false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://node2:7002/eureka/

  server:
    # 关闭自我保护机制，保证不可用的服务及时剔除
    enable-self-preservation: false
    # 清理间隔（单位毫秒）
    eviction-interval-timer-in-ms: 2000