spring:
  application:
    name: eureka-server

server:
  port: 7001

eureka:
  instance:
    hostname: node1
  #    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    # 服务本身就是注册中心，需要设置为false取消注册（不设置默认true）
    register-with-eureka: false
    # 设置不拉取服务注册信息
    fetch-registry: false
    serviceUrl:
      defaultZone: http://node1:7001/eureka,http://node2:7002/eureka
      # 仅配置其他Eureka服务也可以
  #      defaultZone: http://node2:7002/eureka

  server:
    # 关闭自我保护机制，保证不可用的服务及时剔除
    enable-self-preservation: false
    # 清理间隔（单位毫秒）
    eviction-interval-timer-in-ms: 2000
