####################################################################################################
####################################### 集群版服务注册中心配置 开始 ##################################
####################################################################################################
server:
  port: 7001

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: node1
  #    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    # 配置是否寻找其他Eureka服务注册中心进行注册，集群版Eureka服务需要互相注册，设置为true（不设置默认true）
    register-with-eureka: true
    # 配置是否从服务配置中心拉取服务注册信息，通常只有消费者需要设置为true（不设置默认true）
    fetch-registry: false
    serviceUrl:
      defaultZone: http://node1:7001/eureka,http://node2:7002/eureka
      # 仅配置其他Eureka服务也可以
  #      defaultZone: http://node2:7002/eureka

  server:
    # 关闭自我保护机制，保证不可用的服务及时剔除
    enable-self-preservation: false
    # 清理间隔（单位毫秒）
    eviction-interval-timer-in-ms: 2000
####################################################################################################
####################################### 集群版服务注册中心配置 结束 ##################################
####################################################################################################
