server:
  port: 9001

spring:
  application:
    name: cloud-consumer-order-service

eureka:
  client:
    # true表示将自己注册进EurekaServer，默认true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合Ribbon使用负载均衡
    # 服务调用方需要设置为true，否则抛出java.lang.IllegalStateException: No instances available for CLOUD-PROVIDER-PAYMENT-SERVICE异常
    fetch-registry: true
    # 检索服务实例清单的时间间隔（单位：秒），默认30秒
    registry-fetch-interval-seconds: 30
    # 当服务获取超时后，最大尝试次数，默认10次
    cache-refresh-executor-exponential-back-off-bound: 10
    serviceUrl:
      defaultZone: http://node1:7001/eureka,http://node2:7002/eureka

